# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Caclulate the Markov Blanket for every node in the graph.
#' This is done by default whenever a graph is returned from an algorithm,
#' but it can also be used for graphs loaded from files or adj. mats.
#'
#' @param list The graph object
#' @export
#' @examples
#' mat <- matrix(sample(c(0,1), 16, replace=TRUE), nrow=4)
#' nodes <- c("X1", "X2", "X3", "X4")
#' g <- rCausalMGM::adjMat2Graph(mat, nodes, directed=TRUE)
#' g[["markov.blankets"]] <- rCausalMGM::calculateMarkovBlankets(g)
NULL

#' Save a graph to a file
#'
#' @param list The graph object
#' @param filename The graph file
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgm(data.n100.p25)
#' rCausalMGM::saveGraph(g, "graphs/mgm_graph.txt")
saveGraph <- function(graph, filename) {
    invisible(.Call(`_rCausalMGM_saveGraph`, graph, filename))
}

#' Load a graph from a file
#'
#' @param filename The graph file
#' @return The graph as a List object, which can be passed into search functions
#' @export
loadGraph <- function(filename) {
    .Call(`_rCausalMGM_loadGraph`, filename)
}

#' Convert an adjacency matrix into a graph
#'
#' @param adj The adjacency matrix, NxN
#' @param nodes The names of the nodes, length N
#' @param directed TRUE if the graph should be directed, default FALSE
#' @return The graph representation of the adjacency list
#' @export
#' @examples
#' mat <- matrix(sample(c(0,1), 16, replace=TRUE), nrow=4)
#' mat[upper.tri(mat)] <- 0
#' nodes <- c("X1", "X2", "X3", "X4")
#' g <- rCausalMGM::adjMat2Graph(mat, nodes, directed=TRUE)
adjMat2Graph <- function(adj, nodes, directed = FALSE) {
    .Call(`_rCausalMGM_adjMat2Graph`, adj, nodes, directed)
}

#' Display a graph object as text
#'
#' @param graph The graph object
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgm(data.n100.p25)
#' rCausalMGM::printGraph(g)
printGraph <- function(graph) {
    invisible(.Call(`_rCausalMGM_printGraph`, graph))
}

#' Create the completed partially directed acyclic graph (CPDAG) for the input directed acyclic graph (DAG). The CPDAG represents the Markov equivalence class of the true cauasl DAG. The PC algorithms are only identifiable up to the Markov equivalence class, so assessments of causal structure recovery should be compared to the CPDAG rather than the causal DAG.
#'
#' @param graph The graph object used to generate the CPDAG. Should be the ground-truth causal DAG
#' @return The CPDAG corresponding to the input DAG
#' @export
#' @examples
#' data(dag_n10000_p10)
#' cpdag <- rCausalMGM::cpdag(dag_n10000_p10)
cpdag <- function(graph) {
    .Call(`_rCausalMGM_cpdag`, graph)
}

#' Create the moral graph for the input directed acyclic graph (DAG). The moral graph is the equivalent undirected representation corresponding to the input DAG.
#'
#' @param graph The graph object used to generate the moral graph. Should be the ground-truth causal DAG
#' @return The moral graph corresponding to the input DAG
#' @export
#' @examples
#' data(dag_n10000_p10)
#' moral <- rCausalMGM::moral(dag_n10000_p10)
moral <- function(graph) {
    .Call(`_rCausalMGM_moral`, graph)
}

#' Create the skeleton graph for the input directed acyclic graph (DAG). The skeleton graph is the undirected graph that contains the same adjacencies as the input DAG.
#'
#' @param graph The graph object used to generate the skeleton graph. Should be the ground-truth causal DAG
#' @return The skeleton graph corresponding to the input DAG
#' @export
#' @examples
#' data(dag_n10000_p10)
#' moral <- rCausalMGM::skeleton(dag_n10000_p10)
skeleton <- function(graph) {
    .Call(`_rCausalMGM_skeleton`, graph)
}

#' Create the partial ancestral graph (PAG) for the input directed acyclic graph (DAG). The PAG represents the Markov equivalence class of the true cauasl MAG. The FCI algorithms are only identifiable up to the Markov equivalence class, so assessments of causal structure recovery should be compared to the PAG rather than the causal MAG.
#'
#' @param graph The graph object used to generate the PAG. Should be the ground-truth causal DAG
#' @param latent The names of latent (unobserved) variables in the causal DAG. The default is NULL.
#' @return The PAG corresponding to the input DAG
#' @export
#' @examples
#' data(dag_n10000_p10)
#' cpdag <- rCausalMGM::pag(dag_n10000_p10)
pag <- function(graph, latent = NULL) {
    .Call(`_rCausalMGM_pag`, graph, latent)
}

#' Calculate the skeleton Structural Hamming Distance (SHD) between two graphs. This only counts the missing and added edges, and does not consider edge orientation
#'
#' @param graph1 A graph object
#' @param graph2 A graph object
#' @return The skeleton SHD btween the two graph objects
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgm(data.n100.p25)
#' rCausalMGM::printGraph(g)
skeletonSHD <- function(graph1, graph2) {
    .Call(`_rCausalMGM_skeletonSHD`, graph1, graph2)
}

#' Calculate the orientation Structural Hamming Distance (SHD) between two graphs. This only counts the incorrect edge endpoints for edges present in both graphs, and does not consider differences in the graph skeleton. Each different endpoint adds 0.5 to the orientation SHD (i.e. A o-> B vs. A --> B). Thus, a completely misoriented edge adds 1 to the orientation SHD (i.e. A o-o B vs. A <-- B).
#'
#' @param graph1 A graph object
#' @param graph2 A graph object
#' @return The skeleton SHD btween the two graph objects
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgm(data.n100.p25)
#' rCausalMGM::printGraph(g)
orientationSHD <- function(graph1, graph2) {
    .Call(`_rCausalMGM_orientationSHD`, graph1, graph2)
}

#' Calculate the Structural Hamming Distance (SHD) between two graphs. This is the sum of the skeleton SHD and the orientation SHD.
#'
#' @param graph1 A graph object
#' @param graph2 A graph object
#' @return The SHD btween the two graph objects
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgm(data.n100.p25)
#' rCausalMGM::printGraph(g)
SHD <- function(graph1, graph2) {
    .Call(`_rCausalMGM_SHD`, graph1, graph2)
}

#' Calculate the skeleton precision, recall, F1, and Matthew's Correlation Coefficient (MCC) between an estimated and ground truth graph.
#'
#' @param estimate An estimated graph object
#' @param groundTruth A ground truth graph object
#' @return The skeleton precision, recall, F1, and MCC, between the two graph objects
#' @export
#' @examples
#' data("train_n10000_p10")
#' data("dag_n10000_p10")
#' g <- rCausalMGM::cpcStable(train_n10000_p10, rCausalMGM::cpdag(dag_n10000_p10))
#' rCausalMGM::prMetricsSkeleton(g)
prMetricsSkeleton <- function(estimate, groundTruth) {
    .Call(`_rCausalMGM_prMetricsSkeleton`, estimate, groundTruth)
}

#' Calculate the orientation precision, recall, F1, and Matthew's Correlation Coefficient (MCC) between an estimated and ground truth graph.
#'
#' @param estimate An estimated graph object
#' @param groundTruth A ground truth graph object of the same type as the estimated graph object
#' @param groundTruthDAG A ground truth graph object containing the true causal DAG. Only necessary for calculating the or precision, recall, F1, and MCC for partial ancestral graphs (PAGs)
#' @return The orientation precision, recall, F1, and MCC, between the two graph objects
#' @export
#' @examples
#' data("train_n10000_p10")
#' data("dag_n10000_p10")
#' g <- rCausalMGM::cpcStable(train_n10000_p10)
#' rCausalMGM::prMetricsOrientation(g, rCausalMGM::cpdag(dag_n10000_p10))
prMetricsOrientation <- function(estimate, groundTruth, groundTruthDAG = NULL) {
    .Call(`_rCausalMGM_prMetricsOrientation`, estimate, groundTruth, groundTruthDAG)
}

#' Calculate the precision, recall, F1, and Matthew's Correlation Coefficient (MCC) for the skeleton and orientations of an estimated graph compared to the ground truth. This is the concatenated output of the skeleton PR metrics and the orientation PR metrics.
#' @param estimate An estimated graph object
#' @param groundTruth A ground truth graph object of the same type as the estimated graph object
#' @param groundTruthDAG A ground truth graph object containing the true causal DAG. Only necessary for calculating the or precision, recall, F1, and MCC for partial ancestral graphs (PAGs)
#' @return The orientation precision, recall, F1, and MCC, between the two graph objects
#' @export
#' @examples
#' data("train_n10000_p10")
#' data("dag_n10000_p10")
#' g <- rCausalMGM::cpcStable(train_n10000_p10)
#' rCausalMGM::prMetrics(g, rCausalMGM::cpdag(dag_n10000_p10))
prMetrics <- function(estimate, groundTruth, groundTruthDAG = NULL) {
    .Call(`_rCausalMGM_prMetrics`, estimate, groundTruth, groundTruthDAG)
}

#' Calculate the SHD, precision, recall, F1, and Matthew's Correlation Coefficient (MCC) for the skeleton and orientations of an estimated graph compared to the ground truth. This is the concatenated output of the skeleton PR metrics and the orientation PR metrics.
#' @param estimate An estimated graph object
#' @param groundTruth A ground truth graph object of the same type as the estimated graph object
#' @param groundTruthDAG A ground truth graph object containing the true causal DAG. Only necessary for calculating the or precision, recall, F1, and MCC for partial ancestral graphs (PAGs)
#' @return The orientation precision, recall, F1, and MCC, between the two graph objects
#' @export
#' @examples
#' data("train_n10000_p10")
#' data("dag_n10000_p10")
#' g <- rCausalMGM::cpcStable(train_n10000_p10)
#' rCausalMGM::allMetrics(g, rCausalMGM::cpdag(dag_n10000_p10))
allMetrics <- function(estimate, groundTruth, groundTruthDAG = NULL) {
    .Call(`_rCausalMGM_allMetrics`, estimate, groundTruth, groundTruthDAG)
}

#' Calculate the MGM graph on a dataset
#'
#' @param df The dataframe
#' @param lambda A vector of three lambda values - the first for continuous-continuous interaction, the second for continuous-discrete, and the third for discrete-discrete. Defaults to c(0.2, 0.2, 0.2). If a single value is provided, all three values in the vector will be set to that value.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated MGM graph
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgm(data.n100.p25)
mgm <- function(df, lambda = as.numeric( c(0.2, 0.2, 0.2)), rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_mgm`, df, lambda, rank, verbose)
}

#' Calculate the solution path for an MGM graph on a dataset
#'
#' @param df The dataframe
#' @param lambdas A range of lambda values used to calculate a solution path for MGM. If NULL, lambdas is set to nLambda logarithmically spaced values from 10*sqrt(log10(p)/n) to sqrt(log10(p)/n). Defaults to NULL.
#' @param nLambda The number of lambda values to fit an MGM for when lambdas is NULL
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated MGM graph
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgmPath(data.n100.p25)
mgmPath <- function(df, lambdas = NULL, nLambda = 30L, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_mgmPath`, df, lambdas, nLambda, rank, verbose)
}

#' Calculate the solution path for an MGM graph on a dataset
#'
#' @param df The dataframe
#' @param lambdas A range of lambda values used to calculate a solution path for MGM. If NULL, lambdas is set to nLambda logarithmically spaced values from 10*sqrt(log10(p)/n) to sqrt(log10(p)/n). Defaults to NULL.
#' @param nLambda The number of lambda values to fit an MGM for when lambdas is NULL
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated MGM graph
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgmCV(data.n100.p25)
mgmCV <- function(df, lambdas = NULL, nLambda = 30L, nfolds = 10L, foldid = NULL, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_mgmCV`, df, lambdas, nLambda, nfolds, foldid, rank, verbose)
}

#' Calculates the optimal lambda values for the MGM algorithm using StEPS and run the algorithm using those values. Optimal values are printed
#'
#' @param df The dataframe
#' @param lambdas A range of lambda values assessed for stability by the StEPS algorithm. If NULL, lambdas is set to nLambda logarithmically spaced values from 10*sqrt(log10(p)/n) to sqrt(log10(p)/n). Defaults to NULL.
#' @param nLambda The number of lambda values to fit an MGM for when lambdas is NULL
#' @param g The gamma parameter for STEPS. Defaults to 0.05
#' @param numSub The number of subsets to split the data into. Defaults to 20
#' @param subSize The size of the subsamples used for STEPS. If the value is -1, the size of the subsamples is set to floor(10*sqrt(n)). If the value is in the range (0,1), the size of the subsamples is set to floor(subSize * n). Otherwise, if subSize is in the range [1,n), the size of the subsamples is set to subSize. Defaults to -1.
#' @param leaveOneOut If TRUE, performs leave-one-out subsampling. Defaults to FALSE.
#' @param computeStabs If TRUE, stability values are calculated. Defaults to FALSE.
#' @param threads The number of consumer threads to create during multi-threaded steps. If -1, defaults to number of availible processors.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated MGM graph
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::steps(data.n100.p25)
steps <- function(df, lambdas = NULL, nLambda = 20L, g = 0.05, numSub = 20L, subSize = -1L, leaveOneOut = FALSE, computeStabs = FALSE, threads = -1L, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_steps`, df, lambdas, nLambda, g, numSub, subSize, leaveOneOut, computeStabs, threads, rank, verbose)
}

#' Runs the causal algorithm PC-Stable on a dataset
#'
#' @param df The dataframe
#' @param initialGraph An initial undirected graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param threads The number of consumer threads to create during multi-threaded steps. If -1, defaults to number of availible processors.
#' @param fdr Whether or not to run with FDR correction for the adjacencies.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::pcStable(data.n100.p25, initialGraph = ig)
pcStable <- function(df, initialGraph = NULL, alpha = 0.05, threads = -1L, fdr = FALSE, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_pcStable`, df, initialGraph, alpha, threads, fdr, rank, verbose)
}

#' Runs the causal algorithm CPC-Stable on a dataset
#'
#' @param df The dataframe
#' @param initialGraph An initial undirected graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param threads The number of consumer threads to create during multi-threaded steps. If -1, defaults to number of availible processors.
#' @param fdr Whether or not to run with FDR correction for the adjacencies.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::cpcStable(data.n100.p25, initialGraph = ig)
cpcStable <- function(df, initialGraph = NULL, alpha = 0.05, threads = -1L, fdr = FALSE, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_cpcStable`, df, initialGraph, alpha, threads, fdr, rank, verbose)
}

#' Runs the causal algorithm PC-Max on a dataset
#'
#' @param df The dataframe
#' @param initialGraph An initial undirected graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param threads The number of consumer threads to create during multi-threaded steps. If -1, defaults to number of availible processors.
#' @param fdr Whether or not to run with FDR correction for the adjacencies.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::pcMax(data.n100.p25, initialGraph = ig)
pcMax <- function(df, initialGraph = NULL, alpha = 0.05, threads = -1L, fdr = FALSE, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_pcMax`, df, initialGraph, alpha, threads, fdr, rank, verbose)
}

#' Runs the causal algorithm PC50 on a dataset
#'
#' @param df The dataframe
#' @param initialGraph An initial undirected graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param threads The number of consumer threads to create during multi-threaded steps. If -1, defaults to number of availible processors.
#' @param fdr Whether or not to run with FDR correction for the adjacencies.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::pc50(data.n100.p25, initialGraph = ig)
pc50 <- function(df, initialGraph = NULL, alpha = 0.05, threads = -1L, fdr = FALSE, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_pc50`, df, initialGraph, alpha, threads, fdr, rank, verbose)
}

#' Runs the causal algorithm FCI-Stable on a dataset
#'
#' @param df The dataframe
#' @param initialGraph An initial undirected graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param threads The number of consumer threads to create during multi-threaded steps. If -1, defaults to number of availible processors.
#' @param fdr Whether or not to run with FDR correction for the adjacencies.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::fciStable(data.n100.p25, initialGraph = ig)
fciStable <- function(df, initialGraph = NULL, alpha = 0.05, threads = -1L, fdr = FALSE, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_fciStable`, df, initialGraph, alpha, threads, fdr, rank, verbose)
}

#' Runs the causal algorithm CFCI-Stable on a dataset
#'
#' @param df The dataframe
#' @param initialGraph An initial undirected graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param threads The number of consumer threads to create during multi-threaded steps. If -1, defaults to number of availible processors.
#' @param fdr Whether or not to run with FDR correction for the adjacencies.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::cfci(data.n100.p25, initialGraph = ig)
cfci <- function(df, initialGraph = NULL, alpha = 0.05, threads = -1L, fdr = FALSE, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_cfci`, df, initialGraph, alpha, threads, fdr, rank, verbose)
}

#' Runs the causal algorithm FCI-Max on a dataset
#'
#' @param df The dataframe
#' @param initialGraph An initial undirected graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param threads The number of consumer threads to create during multi-threaded steps. If -1, defaults to number of availible processors.
#' @param fdr Whether or not to run with FDR correction for the adjacencies.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::fciMax(data.n100.p25, initialGraph = ig)
fciMax <- function(df, initialGraph = NULL, alpha = 0.05, threads = -1L, fdr = FALSE, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_fciMax`, df, initialGraph, alpha, threads, fdr, rank, verbose)
}

#' Runs the causal algorithm FCI50 Stable on a dataset
#'
#' @param df The dataframe
#' @param initialGraph An initial undirected graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param threads The number of consumer threads to create during multi-threaded steps. If -1, defaults to number of availible processors.
#' @param fdr Whether or not to run with FDR correction for the adjacencies.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::fci50(data.n100.p25, initialGraph = ig)
fci50 <- function(df, initialGraph = NULL, alpha = 0.05, threads = -1L, fdr = FALSE, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_fci50`, df, initialGraph, alpha, threads, fdr, rank, verbose)
}

#' Runs bootstrapping for a selected causal discovery algorithm on the dataset.
#'
#' @param df The dataframe
#' @param algorithm string indicating the name of the causal discovery algorithm to bootstrap. Causal discovery algorithms can be run alone or with mgm to learn an initial graph. Options include "mgm", "pc", "cpc", "pcm", "pc50", "fci", "cfci", "fcim", "mgm-pc", "mgm-cpc", "mgm-pcm", "mgm-pc50", "mgm-fci", "mgm-cfci", "mgm-fcim", "mgm-fci50." The default value is set to "mgm-pc50."
#' @param ensemble Method for construncting an ensemble graph from bootstrapped graphs. Options include "highest", which orients edges according to the orientation with the highest bootstrap probability, or "majority", which only orients edges if they have an orientation with a bootstrap probability > 0.5. Otherwise, the adjacency is included but the edge is left unoreineted. The default value is "highest."
#' @param lambda A vector of three lambda values - the first for continuous-continuous interaction, the second for continuous-discrete, and the third for discrete-discrete. Defaults to c(0.2, 0.2, 0.2). If a single value is provided, all three values in the vector will be set to that value.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param numBoots The number of bootstrap samples to run. Defaults to 20.
#' @param threads The number of consumer threads to create during multi-threaded steps. If -1, defaults to number of availible processors.
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph with a table of edge stabilities
#' @export
#' @examples
#' data("data.n100.p25")
#' g.boot <- rCausalMGM::bootstrap(data.n100.p25)
bootstrap <- function(df, algorithm = as.character( c("mgm-pc50", "mgm", "pc", "cpc", "pcm", "pc50", "fci", "cfci", "fcim", "mgm-pc", "mgm-cpc", "mgm-pcm", "mgm-fci", "mgm-cfci", "mgm-fcim", "mgm-fci50")), ensemble = as.character( c("highest", "majority")), lambda = as.numeric( c(0.2, 0.2, 0.2)), alpha = 0.05, numBoots = 20L, threads = -1L, rank = FALSE, verbose = FALSE) {
    .Call(`_rCausalMGM_bootstrap`, df, algorithm, ensemble, lambda, alpha, numBoots, threads, rank, verbose)
}

#' Runs the Grow-Shrink algorithm to find the Markov blanket of a feature in a dataset
#'
#' @param df The dataframe
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The list of features in the Markov Blanket and the BIC score
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::growShrinkMB(data.n100.p25)
growShrinkMB <- function(df, target, penalty = 1, rank = FALSE, threads = -1L, verbose = FALSE) {
    .Call(`_rCausalMGM_growShrinkMB`, df, target, penalty, rank, threads, verbose)
}

#' Runs the GRaSP causal discovery algorithm on the dataset 
#'
#' @param df The dataframe
#' @param rank Whether or not to use rank-based associations as opposed to linear
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The list of features in the Markov Blanket and the BIC score
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::markovBlanket(data.n100.p25)
grasp <- function(df, initialGraph = NULL, depth = 2L, numStarts = 3L, penalty = 1, rank = FALSE, threads = -1L, verbose = FALSE) {
    .Call(`_rCausalMGM_grasp`, df, initialGraph, depth, numStarts, penalty, rank, threads, verbose)
}

