# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Save a graph to a file
#'
#' @param list The graph object
#' @param filename The graph file
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgm(data.n100.p25)
#' rCausalMGM::saveGraph(g, "graphs/mgm_graph.txt")
saveGraph <- function(list, filename) {
    invisible(.Call(`_rCausalMGM_saveGraph`, list, filename))
}

#' Load a graph from a file
#'
#' @param filename The graph file
#' @return The graph as a List object, which can be passed into search functions
#' @export
loadGraph <- function(filename) {
    .Call(`_rCausalMGM_loadGraph`, filename)
}

#' Convert an adjacency matrix into a graph
#'
#' @param adj The adjacency matrix, NxN
#' @param nodes The names of the nodes, length N
#' @param directed TRUE if the graph should be directed, default FALSE
#' @return The graph representation of the adjacency list
#' @export
#' @examples
#' mat <- matrix(sample(c(0,1), 16, replace=TRUE), nrow=4)
#' nodes <- c("X1", "X2", "X3", "X4")
#' g <- rCausalMGM::adjMat2Graph(mat, nodes, directed=TRUE)
adjMat2Graph <- function(adj, nodes, directed = as.logical( c(0))) {
    .Call(`_rCausalMGM_adjMat2Graph`, adj, nodes, directed)
}

#' Display a graph object as text
#'
#' @param graph The graph object
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgm(data.n100.p25)
#' rCausalMGM::printGraph(g)
printGraph <- function(graph) {
    invisible(.Call(`_rCausalMGM_printGraph`, graph))
}

#' Calculate the MGM graph on a dataset
#'
#' @param df The dataframe
#' @param lambda A vector of three lambda values - the first for continuous-continuous interaction, the second for continuous-discrete, and the third for discrete-discrete. Defaults to c(0.2, 0.2, 0.2)
#' @param maxDiscrete The maximum number of unique values a variable can have before being considered continuous. Defaults to 5
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated MGM graph
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::mgm(data.n100.p25)
mgm <- function(df, lambda = as.numeric( c(0.2, 0.2, 0.2)), maxDiscrete = 5L, verbose = as.logical( c(0))) {
    .Call(`_rCausalMGM_mgm`, df, lambda, maxDiscrete, verbose)
}

#' Calculate the optimal lambda values for the MGM algorithm and run the algorithm using those values. Optimal values are printed
#'
#' @param df The dataframe
#' @param maxDiscrete The maximum number of unique values a variable can have before being considered continuous. Defaults to 5
#' @param lambda A vector of the lambda values to test. Defaults to c(0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85)
#' @param g The gamma parameter for STEPS. Defaults to 0.05
#' @param numSub The number of subsets to split the data into. Defaults to 20
#' @param leaveOneOut If TRUE, performs leave-one-out subsampling. Defaults to FALSE.
#' @param computeStabs If TRUE, stability values are calculated. Defaults to FALSE.
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated MGM graph
#' @export
#' @examples
#' data("data.n100.p25")
#' g <- rCausalMGM::steps(data.n100.p25)
steps <- function(df, maxDiscrete = 5L, lambda = as.numeric( c(0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85)), g = 0.05, numSub = 20L, leaveOneOut = as.logical( c(0)), computeStabs = as.logical( c(0)), verbose = as.logical( c(0))) {
    .Call(`_rCausalMGM_steps`, df, maxDiscrete, lambda, g, numSub, leaveOneOut, computeStabs, verbose)
}

#' Runs the causal algorithm PC Stable on a dataset
#'
#' @param df The dataframe
#' @param maxDiscrete The maximum number of unique values a variable can have before being considered continuous. Defaults to 5
#' @param initialGraph The MGM graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::pcStable(data.n100.p25, initialGraph = ig)
pcStable <- function(df, maxDiscrete = 5L, initialGraph = NULL, alpha = 0.05, verbose = as.logical( c(0))) {
    .Call(`_rCausalMGM_pcStable`, df, maxDiscrete, initialGraph, alpha, verbose)
}

#' Runs the causal algorithm CPC Stable on a dataset
#'
#' @param df The dataframe
#' @param maxDiscrete The maximum number of unique values a variable can have before being considered continuous. Defaults to 5
#' @param initialGraph The MGM graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::cpcStable(data.n100.p25, initialGraph = ig)
cpcStable <- function(df, maxDiscrete = 5L, initialGraph = NULL, alpha = 0.05, verbose = as.logical( c(0))) {
    .Call(`_rCausalMGM_cpcStable`, df, maxDiscrete, initialGraph, alpha, verbose)
}

#' Runs the causal algorithm PC Max on a dataset
#'
#' @param df The dataframe
#' @param maxDiscrete The maximum number of unique values a variable can have before being considered continuous. Defaults to 5
#' @param initialGraph The MGM graph to use as a starting point. If NULL, a full graph will be used. Defaults to NULL.
#' @param alpha The p value below which results are considered significant. Defaults to 0.05.
#' @param verbose Whether or not to output additional information. Defaults to FALSE.
#' @return The calculated search graph
#' @export
#' @examples
#' data("data.n100.p25")
#' ig <- rCausalMGM::mgm(data.n100.p25)
#' g <- rCausalMGM::pcMax(data.n100.p25, initialGraph = ig)
pcMax <- function(df, maxDiscrete = 5L, initialGraph = NULL, alpha = 0.05, verbose = as.logical( c(0))) {
    .Call(`_rCausalMGM_pcMax`, df, maxDiscrete, initialGraph, alpha, verbose)
}

rcpparma_hello_world <- function() {
    .Call(`_rCausalMGM_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_rCausalMGM_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_rCausalMGM_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_rCausalMGM_rcpparma_bothproducts`, x)
}

